version: "3"
services:
  mysql:
    image: mysql
    environment:
      MYSQL_DATABASE: cars
      MYSQL_ROOT_PASSWORD: 123
    ports:
      - "3307:3306"
  app:
    build:
      context: .
      target: dev
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=development
    depends_on:
      - mysql
